platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(
    File.dirname(__FILE__), 'Flutter', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)$/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run flutter pub get"
end

def flutter_version_name
  generated_xcode_build_settings_path = File.expand_path(File.join(
    File.dirname(__FILE__), 'Flutter', 'Flutter-Generated.xcconfig'), __FILE__)
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_BUILD_NAME\=(.*)$/)
    return matches[1].strip if matches
  end
  return '1.0.0+1'
end

def flutter_version_code
  generated_xcode_build_settings_path = File.expand_path(File.join(
    File.dirname(__FILE__), 'Flutter', 'Flutter-Generated.xcconfig'), __FILE__)
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_BUILD_NUMBER\=(.*)$/)
    return matches[1].strip if matches
  end
  return '1'
end

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_build_settings Dir.pwd
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
      ]
    end
  end
end
